name: Continuous Integration
on: [push]
jobs:
    ci:
        name: Continuous Integration
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ ubuntu-latest ]
                php-versions: [ '8.0' ]
        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: 'password'
                ports:
                    - 3306:3306
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, xml, ctype, iconv, intl
                  coverage: xdebug
            - name: Cache composer dependencies
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-php-
            - name: Install Composer dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            - name: Run phpunit tests
              run: ./vendor/bin/phpunit